name: tf_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - tensorflow==2.12.0
      - pandas==1.5.3
      - numpy==1.21.6
      - matplotlib==3.5.3
      - seaborn==0.11.2
      - scikit-learn==1.1.3
      - jupyter